# Generated by Django 4.1.2 on 2022-11-02 12:45

import django.core.validators
from django.db import migrations, models
import users.validation


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[users.validation.ValidationUser.password_validation, django.core.validators.MinLengthValidator(8)], verbose_name='password'),
        ),
    ]
