version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9.0-browsers
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: bookstore
          POSTGRES_DB: bookstore
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Migration
          command: pipenv run python manage.py migrate
      - run:
          name: Run tests
          command: pipenv run python manage.py test
workflows:
  version: 2
  testing:
    jobs:
      - test
