version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
      - image: circleci/postgres:13.3-postgis
        environment:
          POSTGRES_USER: bookstore
          POSTGRES_DB: bookstore
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: Running migrations
          command: |
            . venv/bin/activate
            python manage.py migrate --skip-checks
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test shop
