version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Installing dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - python/save-cache
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test
