version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Migrate
          command: |
            pipenv run python manage.py migrate
      - run:
          name: Run django tests
          command: |
            pipenv run python manage.py test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
