# Generated by Django 4.1.2 on 2022-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='materials',
            field=models.CharField(default='Paper', max_length=30),
            preserve_default=False,
        ),
    ]
